In [3]:
# Getting the CSV files ready for hydrating the tweet IDs
# Source: https://ieee-dataport.org/open-access/coronavirus-covid-19-tweets-dataset Retrieved July 2022

import pandas as pd
#IEEE data port COVID-19 with sentiments datasets
df1=pd.read_csv("corona_tweets_469.csv", header=None)
df2=pd.read_csv("corona_tweets_470.csv", header=None)
df3=pd.read_csv("corona_tweets_105.csv", header=None)
df4=pd.read_csv("corona_tweets_468.csv", header=None)
df5=pd.read_csv("corona_tweets_104.csv", header=None)
df6=pd.read_csv("corona_tweets_103.csv", header=None)

# only keeping the first column, removing the sentiment column and saving in new data frames
df1Edited=df1[0]
df2Edited=df2[0]
df3Edited=df3[0]
df4Edited=df4[0]
df5Edited=df5[0]
df6Edited=df6[0]

#saving the new datasets without sentiment column into a new csv file 
df1Edited.to_csv("ready_corona_tweets_469.csv", index=False, header=None)
df2Edited.to_csv("ready_corona_tweets_470.csv", index=False, header=None)
df3Edited.to_csv("ready_corona_tweets_105.csv", index=False, header=None)
df4Edited.to_csv("ready_corona_tweets_468.csv", index=False, header=None)
df5Edited.to_csv("ready_corona_tweets_468.csv", index=False, header=None)
df6Edited.to_csv("ready_corona_tweets_103.csv", index=False, header=None)

In [5]:
# concatenation all orginial IEEE data port COVID-19 with sentiments datasets and rename the columns
dfConcat=pd.concat([df1,df2,df3,df4,df5,df6])
dfConcat.rename(columns={0:'id',1:'Sentiment'}, inplace=True)

In [6]:
dfConcat

                          id  Sentiment
0        1410093363320147973  -0.152778
1        1410093363844423682   0.100000
2        1410093363743793154   0.138889
3        1410093364364550147   1.000000
4        1410093364607807489   0.000000
...                      ...        ...
3880993  1277820427138555904   0.000000
3880994  1277820427205664768  -0.062500
3880995  1277820427293745153   0.150000
3880996  1277820427255963649   0.225000
3880997  1277820427260366848   0.000000

[17774458 rows x 2 columns]

In [7]:
# loading the resulted dataset from the hydration process
dfAll=pd.read_csv("ready_corona_tweets_all.csv")

<ipython-input-7-ecff6115397d>:1: DtypeWarning: Columns (0,1,2,3,4,5,6,7,10,11,12,15,16,17,18,19,20,22,23,28,29,30,33,34) have mixed types. Specify dtype option on import or set low_memory=False.
  dfAll=pd.read_csv("ready_corona_tweets_all.csv")

In [8]:
dfAll

,coordinates,created_at,hashtags,media,urls,favorite_count,id,in_reply_to_screen_name,in_reply_to_status_id,in_reply_to_user_id,...,user_followers_count,user_friends_count,user_listed_count,user_location,user_name,user_screen_name,user_statuses_count,user_time_zone,user_urls,user_verified
0,NaN,Tue Jun 30 04:25:57 +0000 2020,NaN,NaN,NaN,0,1277820648123969536,NaN,NaN,NaN,...,13.0,47.0,0.0,"Panama City Beach, FL",Andrew Brissette,abrissette94,60.0,NaN,NaN,False
1,NaN,Tue Jun 30 04:25:57 +0000 2020,NaN,NaN,https://twitter.com/benandjerrys/status/127728...,2,1277820645041147904,NaN,NaN,NaN,...,208.0,365.0,0.0,NaN,Christa Squire,Christa_Vi,4460.0,NaN,NaN,False
2,NaN,Tue Jun 30 04:25:58 +0000 2020,NaN,NaN,https://twitter.com/i/events/1277716877960073216,0,1277820650783215616,NaN,NaN,NaN,...,2.0,39.0,0.0,NaN,Ali Khan,AliKhan40489666,21.0,NaN,NaN,False
3,NaN,Tue Jun 30 04:25:58 +0000 2020,NaN,https://twitter.com/QuickTake/status/127768814...,NaN,0,1277820649990270976,NaN,NaN,NaN,...,776.0,963.0,1.0,"San Diego, CA",Juan Gonzalez,Abc123juice,104609.0,NaN,NaN,False
4,NaN,Tue Jun 30 04:25:58 +0000 2020,NaN,NaN,NaN,0,1277820650304835584,NaN,NaN,NaN,...,8084.0,462.0,0.0,ทอดไข่อยู่🍳,🪸🫧mu✿hyun,bebehyunn,429830.0,NaN,https://youtu.be/2IkoKhr6Tss,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6290994,NaN,Mon Jun 29 14:40:01 +0000 2020,NaN,NaN,NaN,0,1277612791562555393,NaN,NaN,NaN,...,47.0,411.0,0.0,NaN,JBJuengerman,James40106973,5888.0,NaN,NaN,False
6290995,NaN,Mon Jun 29 14:40:00 +0000 2020,NaN,https://twitter.com/websmartmedia/status/12776...,https://ecs.page.link/wUv2J,1,1277612789926895617,NaN,NaN,NaN,...,225.0,689.0,4.0,"Pitlochry, Scotland",Web Smart Media,websmartmedia,2249.0,NaN,https://www.websmartmedia.co.uk/,False
6290996,NaN,Mon Jun 29 14:40:02 +0000 2020,NaN,NaN,NaN,0,1277612796226662401,NaN,NaN,NaN,...,464.0,1664.0,0.0,"Delhi, India",Sachin Chaurasia,i5achin_,13594.0,NaN,NaN,False
6290997,NaN,Mon Jun 29 14:40:00 +0000 2020,NaN,NaN,https://www.clickorlando.com/news/local/2020/0...,2,1277612788156858371,NaN,NaN,NaN,...,146384.0,1535.0,1283.0,"Orlando, FL",News 6 WKMG,news6wkmg,194016.0,NaN,http://www.clickorlando.com,True
6290998,NaN,Mon Jun 29 14:39:56 +0000 2020,Maharashtra Covid_19,NaN,NaN,0,1277612773434744832,NaN,NaN,NaN,...,383.0,58.0,4.0,"Khopoli, India",Hiten Shah 🇮🇳,ChowkidaarShah,72444.0,NaN,NaN,False

In [9]:
# merge the hydrated dataset and the orginal IEEE dataset based on id column 
dfMerged = pd.merge(dfAll, dfConcat, on=['id'], how='left')

In [10]:
dfMerged

,coordinates,created_at,hashtags,media,urls,favorite_count,id,in_reply_to_screen_name,in_reply_to_status_id,in_reply_to_user_id,...,user_friends_count,user_listed_count,user_location,user_name,user_screen_name,user_statuses_count,user_time_zone,user_urls,user_verified,Sentiment
0,NaN,Tue Jun 30 04:25:57 +0000 2020,NaN,NaN,NaN,0,1277820648123969536,NaN,NaN,NaN,...,47.0,0.0,"Panama City Beach, FL",Andrew Brissette,abrissette94,60.0,NaN,NaN,False,0.107143
1,NaN,Tue Jun 30 04:25:57 +0000 2020,NaN,NaN,https://twitter.com/benandjerrys/status/127728...,2,1277820645041147904,NaN,NaN,NaN,...,365.0,0.0,NaN,Christa Squire,Christa_Vi,4460.0,NaN,NaN,False,0.000000
2,NaN,Tue Jun 30 04:25:58 +0000 2020,NaN,NaN,https://twitter.com/i/events/1277716877960073216,0,1277820650783215616,NaN,NaN,NaN,...,39.0,0.0,NaN,Ali Khan,AliKhan40489666,21.0,NaN,NaN,False,0.000000
3,NaN,Tue Jun 30 04:25:58 +0000 2020,NaN,https://twitter.com/QuickTake/status/127768814...,NaN,0,1277820649990270976,NaN,NaN,NaN,...,963.0,1.0,"San Diego, CA",Juan Gonzalez,Abc123juice,104609.0,NaN,NaN,False,-0.500000
4,NaN,Tue Jun 30 04:25:58 +0000 2020,NaN,NaN,NaN,0,1277820650304835584,NaN,NaN,NaN,...,462.0,0.0,ทอดไข่อยู่🍳,🪸🫧mu✿hyun,bebehyunn,429830.0,NaN,https://youtu.be/2IkoKhr6Tss,False,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6292086,NaN,Mon Jun 29 14:40:01 +0000 2020,NaN,NaN,NaN,0,1277612791562555393,NaN,NaN,NaN,...,411.0,0.0,NaN,JBJuengerman,James40106973,5888.0,NaN,NaN,False,0.250000
6292087,NaN,Mon Jun 29 14:40:00 +0000 2020,NaN,https://twitter.com/websmartmedia/status/12776...,https://ecs.page.link/wUv2J,1,1277612789926895617,NaN,NaN,NaN,...,689.0,4.0,"Pitlochry, Scotland",Web Smart Media,websmartmedia,2249.0,NaN,https://www.websmartmedia.co.uk/,False,0.225000
6292088,NaN,Mon Jun 29 14:40:02 +0000 2020,NaN,NaN,NaN,0,1277612796226662401,NaN,NaN,NaN,...,1664.0,0.0,"Delhi, India",Sachin Chaurasia,i5achin_,13594.0,NaN,NaN,False,0.200000
6292089,NaN,Mon Jun 29 14:40:00 +0000 2020,NaN,NaN,https://www.clickorlando.com/news/local/2020/0...,2,1277612788156858371,NaN,NaN,NaN,...,1535.0,1283.0,"Orlando, FL",News 6 WKMG,news6wkmg,194016.0,NaN,http://www.clickorlando.com,True,0.000000
6292090,NaN,Mon Jun 29 14:39:56 +0000 2020,Maharashtra Covid_19,NaN,NaN,0,1277612773434744832,NaN,NaN,NaN,...,58.0,4.0,"Khopoli, India",Hiten Shah 🇮🇳,ChowkidaarShah,72444.0,NaN,NaN,False,0.113636

In [11]:
# saving the merged dataset into a new csv file
dfMerged.to_csv("CovidMaskTrainingDatasetRaw.csv",mode='w', encoding='utf-8', index=False, line_terminator='\n')